export const AT = {
  APP_ADD_TOAST: 'APP_ADD_TOAST',
  APP_CLEAR_TOAST: 'APP_CLEAR_TOAST',

  MEALS_TOGGLE_FAVORITE: 'MEALS_TOGGLE_FAVORITE',
  MEALS_UPDATE_FILTERS: 'MEALS_UPDATE_FILTERS',

  SECTION_FETCHING: 'SECTION_FETCHING',
  SECTION_FETCHED: 'SECTION_FETCHED',
  SECTION_REJECTED: 'SECTION_REJECTED',
};
