export const AT = {
  MEALS_TOGGLE_FAVORITE: 'MEALS_TOGGLE_FAVORITE',
  MEALS_UPDATE_FILTERS: 'MEALS_UPDATE_FILTERS',

  PRODUCT_SET_SECTION_FETCHING: 'PRODUCT_SET_SECTION_FETCHING',
  PRODUCT_SET_SECTION_FETCHED: 'PRODUCT_SET_SECTION_FETCHED',
  PRODUCT_SET_SECTION_REJECTED: 'PRODUCT_SET_SECTION_REJECTED',
};
